### PR TITLE
Registering multiple observers

### PR DESCRIPTION
**Pull request by SimonBartels**
This feature refactors the observer usage, allowing to specify a name instead of handing over an instantiated class.

### CODE REVIEW

**Comment by miguelgondu** [comment]
Hey Simon!

It looks good, I'll download and test locally soon. Could I also ask you to update the tests (specifically those in `test_observers.py`)? That way I can get a feel of how you'd like observers to be used in practice.

**Comment by miguelgondu** [comment]
Also: #179

**Comment by miguelgondu** [comment]
Tests pass! :)

**Comment by miguelgondu** [comment]
Hey Simon!

One small question: I've been wondering whether we should add support to have several observers watch the same objective function. I'm starting to need that functionality in my project.

I can hack it by implementing a single observer that handles two different logging logics, so no worries and no rush.

**Comment by SimonBartels** [comment]
Hej Miguel,
how about having a meta observer that just starts all the given observers? The question is how to specify which observers to start...

**Pull request merged**
